defaults: &defaults
  docker:
      - image: circleci/node:10.15.0
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: npm install --no-audit
      - run:
          name: Run audit-ci
          command: npm run audit
      - run:
          name: ESLint
          command: npm run eslint
      - run:
          name: Stylelint
          command: npm run stylelint
      - run:
          name: Run tests
          command: npm run test:coverage --maxWorkers=4
      - run:
          name: Check dependency licenses
          command: npm run licenses
      - run:
          name: Transpile UI components for package
          command: npm run lib
      - run:
          name: Build bundled UI components
          command: npm run build
      - run:
          name: Build style guide
          command: npm run docs:build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - styleguide

  
  deploy-prod-docs:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/
      - add_ssh_keys:
          fingerprints:
            - "17:31:e3:6b:2a:94:4d:33:ed:67:fe:77:b2:55:02:21"
      - run:
          name: Deploy to gh-pages
          command: |
            cd styleguide
            git config --global user.email circleci@circleci
            git config --global user.name CircleCIBot
            git init
            git add -A
            git commit -m 'Docs build [ci skip]'
            git remote add origin https://github.com/quantumblacklabs/kedro-ui.git
            git push origin master:gh-pages --force

workflows:
  version: 2
  regular:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy-prod-docs:
          requires:
              - build
          filters:
            branches:
              only: master
